### ISSUE TITLE
The site is super slow to load all the image of the apps

### ISSUE THREAD

**Issue by makoto** [ensdomains/ensdomains-v2#101]
ens.domains was super slow so I was observing the network traffic. The site is 10MB big and loading lots of logos (the biggest is 3 MB).

<img width="1939" alt="Screenshot 2020-12-06 at 16 57 16" src="https://user-images.githubusercontent.com/2630/101286774-5a2e7f80-37e4-11eb-9995-e962ba36103a.png">

@brantlymillegan when you add image, please compress the image to less than 500kb at least.

@jefflau I think it needs some sort of caching or lazy loading mechanism.

**Comment by brantlymillegan** [comment]
Sorry about that. I'll go through the logos and reduce their file sizes.

**Comment by brantlymillegan** [comment]
I've replaced every logo with with a version of a smaller file size
