### ISSUE TITLE
Homepage not working on iOS browsers

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ensdomains-v2#123]

**Comment by makoto** [comment]
I think this only happens some older version of iOS browser (I tried with 2 iPad and was able to replicate with old one).
After debugging, it showed `ReferenceError: Can't find variable: Bigint` and I don't think I can add polyfill to avoid that.

**Comment by makoto** [comment]
Tried to add babel polyfill but seems not working. Any idea @jefflau ? https://github.com/ensdomains/ens-app/compare/bigint

**Comment by brantlymillegan** [comment]
Here are screenshots of what I see on an iPhone (latest version of iOS) in Chrome (latest version). I also see the exact same problems on Safari on the iPhone.

![IMG_0002](https://user-images.githubusercontent.com/30162762/107779306-66621c00-6d02-11eb-985e-e24651e3bc32.jpeg)
![IMG_0003](https://user-images.githubusercontent.com/30162762/107779308-66fab280-6d02-11eb-80ab-65d2acc37ae4.jpeg)
![IMG_0004](https://user-images.githubusercontent.com/30162762/107779310-66fab280-6d02-11eb-9879-5f74fe2b05ac.jpeg)
![IMG_0005](https://user-images.githubusercontent.com/30162762/107779312-66fab280-6d02-11eb-800f-a02b2842551d.jpeg)

**Comment by makoto** [comment]
Ah ok, I thought it was the homepage of app.ens.domains. Can @jefflau take a look?

**Comment by jefflau** [comment]
I've identified it's just safari, not specifically iOS. I can replicate in the Safari browser. It feels like it must be something to do with some kind of advanced javascript that safari doesn't support by default

**Comment by brantlymillegan** [comment]
@jefflau No, those screenshots above are from Chrome on iOS. And right now I'm testing it and I'm getting the problems on my iPhone in Chrome, Brave, and Safari (all the ones I've checked so far on iOS).

**Comment by jefflau** [comment]
Can't replicate on my local (I get the bug on ens.domains but not on localhost). I'm redeploying now to see if that changes anything.

**Comment by jefflau** [comment]
Super weird. I was going back in time to try and find a commit where the bug didn't exist, now I can't even replicate it. Will pause for now and investigate later. Can't pinpoint what it is right now

**Comment by jefflau** [comment]
I believe this is fixed now.
