### ISSUE TITLE
Add a "Get Started" call to action with a step-by-step guide on how to get started

### ISSUE THREAD

**Issue by TheodoreChu** [ensdomains/ensdomains-v2#139]
ENS Domains could be a gateway into cryptocurrency. People who see value in the legacy domain infrastructure understand and appreciate the scarcity of good names. There is only one `Apple.com` and only one `Amazon.com`. Domain names are scarce digital assets, just like cryptocurrency, so users of legacy domains will likely understand the value of ENS names. Therefore, if we make it easier to get started with ENS domains, more people may be interested in Ethereum and other cryptocurrency.

I think the current landing page and docs are not very helpful for new users. If someone is interested in ENS Domains after seeing the landing page but have no experience with Ethereum, then they will have no idea how to get started. When you click Launch App, you are sent to https://app.ens.domains. There, you will find a "How to use ENS" and a button, but it is useless because it leads back to the home page, https://ens.domains, which doesn't explain how to use ENS. At this point, you have the following options: try to ask people what's going on in the Discord and Discourse (which can lead to abuse), read the docs (which is pretty complicated for people who know nothing about cryptocurrency), try to figure out what's happening on your own (which is tough), or move on with something else. I suspect most people are going to move on.

To make it easier to get started with ENS and Ethereum, I suggest that we replace the first "Launch App" button in the body with a "Get Started" call to action button. This button should be big, like "Decentralised Websites". Add the same button at the bottom before "Get Involved". Keep the Launch App button in the top right of the header. This "Get Started" button should lead to a step-by-step article in the docs on how to get started. This should include:

1. What is Ethereum? How is it different from other cryptocurrencies such as Bitcoin? Perhaps explain what Decentralized Apps are.
2. How to choose a wallet, set it up, and add funds to it. Mention that they need to use a wallet that supports WalletConnect or a Portis, Torus, Authereum, or MEW wallet. Perhaps suggest reputable wallets with ENS integration such as Argent or TrustWallet. Perhaps add a link to Ethereum.org's section on how to pick a wallet: https://ethereum.org/en/wallets/find-wallet/ or a link to WalletConnect.org's section on which wallets support it: https://walletconnect.org/wallets. 
2. How to connect to ENS with your wallet and purchase a name.

There are some blog posts on the internet with step-by-step guides on how to use ENS, but there's nothing official that's easily discoverable. I think it would be extremely helpful to newcomers to have something welcoming and easy to understand for people who like names but don't know much (or anything) about Ethereum or the ecosystem powered by it.

**Comment by brantlymillegan** [comment]
Interesting idea! We're redesigning our Manager right now, will take this into account
