### ISSUE TITLE
Fix spacing for translations

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ensdomains-v2#66]
Try a few different languages and you'll see that some of them mess up the spacing and dont fit into the places that the English words do

**Comment by makoto** [comment]
@brantlymillegan can you explain to me again (with screenshot) where we have issue? I remember it was something to do with Vietnamese but I can 't remember exactly where it's having issues.

**Comment by brantlymillegan** [comment]
@makoto On the homepage, the translations for the words under the big icons "Search," "Register," "Manage" don't fit for DE, PL, FR, ES, RU

![de](https://user-images.githubusercontent.com/30162762/95362538-761cb000-088b-11eb-8a00-cf1b22aa9bea.png)
![PL](https://user-images.githubusercontent.com/30162762/95362554-7ae16400-088b-11eb-89a5-726a10e66ffe.png)
![FR](https://user-images.githubusercontent.com/30162762/95362556-7b79fa80-088b-11eb-9e46-26348b31cfe3.png)
![ES](https://user-images.githubusercontent.com/30162762/95362559-7cab2780-088b-11eb-9434-59ab3ee11298.png)
![RU](https://user-images.githubusercontent.com/30162762/95362788-d3b0fc80-088b-11eb-93be-e9797a1079bf.png)

**Comment by makoto** [comment]
Thanks. Are top pages the only place having issues? Had chat with @jefflau and there isn't easy way to adjust automatically so we may have to add manually adjustment for each case/language. If you can list up all, then we can tackle one by one.

**Comment by brantlymillegan** [comment]
These are the only places I'm aware of where there are problems with spacing

**Comment by jefflau** [comment]
Fixed
