### ISSUE TITLE
Wallet animation not displaying correctly on mobile

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ensdomains-v2#9]
![Screenshot_20200714-200311_Brave](https://user-images.githubusercontent.com/30162762/87518346-048ae800-c635-11ea-9f6e-d0b97a32b493.jpg)

I think this was added when I extended the length of the line of cryptocurrency logos (so they would continue off the page on desktop). Please ensure the length isn't affected, only that the double line of cryptocurrency logos is removed on mobile.

**Comment by jefflau** [comment]
Fixed and deployed
