### ISSUE TITLE
App names scrambled on expansion

### ISSUE THREAD

**Issue by garethfuller** [ensdomains/ensdomains-v2#93]
When expanding the list of apps on the ENS homepage the names of apps seem to be scrambled, i.e. the names don't match the logos, but only on Firefox.

My specs: Firefox 83.0 / macOS Catalina 10.15.7

For reference, I tested on Chrome and everything works as expected.

See 1inch icon / name in this screenshot

![RD8QqkmP jpg large](https://user-images.githubusercontent.com/2406506/100547754-59d03a80-3260-11eb-869a-f94535e2fed6.jpg)

**Comment by brantlymillegan** [comment]
should be fixed now
